server:
  port: 9090

zuul:
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka/
    register-with-eureka: true
    fetch-registry: true

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000